include ../tools/Makefile.base
OUTNAME = t2-book

L10N_REVISION = r

# When we run out of Java HEAP as the svnbook does, ...
# FOP_OPTS="-Xms100m -Xmx200m

# About final book size
FO_XSLTPROC_OPTS = --stringparam page.height 9.82in --stringparam page.width 7.45in

# Uncomment the following line if you'd like to print on A4 paper
# FO_XSLTPROC_OPTS = --stringparam paper.type A4
